### ISSUE TITLE
doesnt work on WIndows 

### ISSUE THREAD

**Issue by raranjak** [zafar142007/WebcamZestureGnome#1]
gives exception when we start application
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further detail
s.
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at java.util.Collections$UnmodifiableList.get(Unknown Source)
        at com.zafar.core.EnterTheZesture.readFromCam(EnterTheZesture.java:32)
        at com.zafar.core.EnterTheZesture.main(EnterTheZesture.java:23)
Exception in thread "main" java.lang.NullPointerException
        at com.zafar.core.EnterTheZesture.readFromCam(EnterTheZesture.java:51)
        at com.zafar.core.EnterTheZesture.main(EnterTheZesture.java:23)

**Comment by zafar142007** [comment]
Tested on other windows 7 machines. Works fine. There may be some application accessing your camera at the time you ran the application.
