### ISSUE TITLE
version2.0 also does not work on  windows

### ISSUE THREAD

**Issue by raranjak** [zafar142007/WebcamZestureGnome#2]
Excepion we got is :+1: 
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further detail
s.
java.lang.NullPointerException
       EE at com.zafar.core.EnterTheZesture.readFromCam(EnterTheZesture.java:32)
        at com.zafar.core.EnterTheZesture.main(EnterTheZesture.java:23)
Exception in thread "main" java.lang.NullPointerException
        at com.zafar.core.EnterTheZesture.readFromCam(EnterTheZesture.java:51)
        at com.zafar.core.EnterTheZesture.main(EnterTheZesture.java:23)

**Comment by zafar142007** [comment]
Tested on other windows 7 machines. Works fine. There may be some application accessing your camera at the time you ran the application.
